POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
  "title": "First class tests",
  "likes": 10
}

###

DELETE http://localhost:3001/api/blogs/5

###

PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{ "likes": 4 }